# Generated by Django 4.1.3 on 2023-03-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
